[project]
name = "graphy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "ast-grep-py>=0.15.0",
    "deepagents>=0.3.0",
    "langchain-openai>=1.1.6",
]
